### ISSUE TITLE
feature request: dark mode

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaComputing/JuliaHub#6]
:night_with_stars:

**Comment by pfitzseb** [comment]
You can now switch to dark mode when logged in.

**Comment by KristofferC** [comment]
Is there an inherent reason it is tied to logged in only?

**Comment by StefanKarpinski** [comment]
It's certainly possible for this to be a remembered in a cookie in the browser, but you also want people who are logged in to get a consistent experience when they log in elsewhere and not have to configure things all over again. If it's per-browser and per-user things get complicated. It seems more important for the service as a whole, since we want to encourage people to log in, to make settings follow the user, not the browser.
